baseURL = "https://pipinstall.me/"
languageCode = "en-us"
title = "Pip Install Me: A Machine Learning Blog"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"



# Menu Bar
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

[params]
  # LoveIt theme version
  version = "0.2.X"

  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # LoveIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # LoveIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "pipinstall.me"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

# Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = ""
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2020
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # LoveIt NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # LoveIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

# Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.webp"
      # LoveIt NEW | 0.2.5 title shown in home page
      title = ""
      # subtitle shown in home page
      subtitle = "Musing about Machine Learning and Deep Learning"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

   # Social config about the author
  [params.social]
    GitHub = "setuc"
    Linkedin = "setuchokshi"
    Twitter = "@setuc"
    Medium = "@setu.chokshi"
    #Youtubechannel = ""

  [params.page]
    # LoveIt NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # LoveIt NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # LoveIt NEW | 0.2.0 whether to enable twemoji
    twemoji = true
    # whether to enable lightgallery
    lightgallery = false
    # LoveIt NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = true
    # LoveIt NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = true
    # LoveIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # LoveIt NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = true
    # LoveIt NEW | 0.2.0 Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to make the table of the contents automatically collapsed
      auto = true
    # LoveIt CHANGED | 0.2.0 KaTeX mathematical formulas
    [params.page.math]
      enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true

    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10

    # LoveIt CHANGED | 0.2.0 social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      HackerNews = true
      Reddit = true
      Instapaper = true
      Pocket = true
      Flipboard = true
      Weibo = true

    # LoveIt NEW | 0.2.0 SEO config
#    [params.page.seo]
#      # Publisher info
#      [params.page.seo.publisher]
#        name = "Setu Chokshi"
#        [params.page.seo.publisher.logo]
#          url = "logo.png"
#          width = 127
#          height = 40
#      # Logo info
#      [params.page.seo.logo]
#        url = "logo.png"
#        width = 127
#        height = 40
#      # Image info
#      [params.page.seo.image]
#        url = "cover.png"
#        width = 800
#        height = 600

  # LoveIt NEW | 0.2.5 TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1


  # LoveIt NEW | 0.2.0 Analytics config
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "UA-29061910-2"
      # whether to anonymize IP
      anonymizeIP = false
      # whether to use cookie
      cookie = true

  # CSS and JS Files CDN config
  [params.cdn]
    # LoveIt NEW | 0.2.0 normalize.css@8.0.1
    normalizeCSS = "https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/0.6.0/modern-normalize.min.css"
    # fontawesome-free@5.13.0
    fontawesomeFreeCSS = "https://use.fontawesome.com/releases/v5.13.0/css/all.css"
    # LoveIt NEW | 0.2.0 simple-icons@2.9.0
    # ("https://cdn.jsdelivr.net/npm/simple-icons@v2/icons/")
    simpleIconsPrefix = "https://cdnjs.cloudflare.com/ajax/libs/simple-icons/2.9.0/simpleicons.svg"
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    animateCSS = "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"
    # smooth-scroll@16.1.3
    smoothScrollJS = "https://cdnjs.cloudflare.com/ajax/libs/smoothscroll/1.4.10/SmoothScroll.min.js"
    # LoveIt NEW | 0.2.0 autocomplete.js@0.37.1
    autocompleteJS = "https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.37.1/autocomplete.jquery.min.js"
    # LoveIt NEW | 0.2.0 lunr.js@2.3.8
    lunrJS = "https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.3.8/lunr.min.js"
    # lazysizes@5.2.0
    lazysizesJS = "https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.0/lazysizes.min.js"
    # LoveIt NEW | 0.2.3 object-fit-images@3.2.4
    objectFitImagesJS = ""
    # LoveIt NEW | 0.2.0 twemoji@12.1.5
    twemojiJS = "https://cdnjs.cloudflare.com/ajax/libs/twemoji/12.0.4/2/twemoji.min.js"
    # lightgallery.js@1.1.3
    # lg-thumbnail.js@1.1.0
    # lg-zoom.js@1.0.1
#    lightgalleryCSS = ""
#    lightgalleryJS = ""
#    lightgalleryThumbnailJS = ""
#    lightgalleryZoomJS = ""
    # LoveIt NEW | 0.2.0 clipboard.js@2.0.6
    clipboardJS = "https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js"
    # sharer.js@0.4.0
    sharerJS = "https://cdnjs.cloudflare.com/ajax/libs/sharer.js/0.4.0/sharer.min.js"
    # typeit@7.0.4
    typeitJS = "https://cdnjs.cloudflare.com/ajax/libs/typeit/7.0.4/typeit.min.js"
    # katex@0.11.1
    katexJS = "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.js"
    # mermaid@8.5.0
    mermaidJS = "https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.5.0/mermaid.min.js"



# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
[author]
  name = "Setu Chokshi"
  #email = ""
  #link = ""

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy config
[privacy]
  # LoveIt DELETED | 0.2.0 privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  # LoveIt CHANGED | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]